<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-NotifyFlow.Worker-791bed8c-8d74-4888-8fd9-07b6ecf10fde</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="RabbitMQ.Client" Version="7.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotifyFlow.Contracts\NotifyFlow.Contracts.csproj" />
  </ItemGroup>
</Project>
